### ISSUE TITLE
Launch fail: claims.map is not a function

### ISSUE THREAD

**Issue by yillkid** [TangleID/TangleID#10]
```shell
$ npm run dev

claims.map is not a function
TypeError: claims.map is not a function
    at getParams (/home/ubuntu/workspace/TangleID/actions/checkTangleUsers.js:18:20)
    at Object.dispatch (/home/ubuntu/workspace/TangleID/middlewares/api.js:53:3)
    at _callee$ (/home/ubuntu/workspace/TangleID/pages/users.js:27:8)
    at tryCatch (/home/ubuntu/workspace/TangleID/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/ubuntu/workspace/TangleID/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/workspace/TangleID/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/ubuntu/workspace/TangleID/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/ubuntu/workspace/TangleID/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
```

**Comment by ender503** [comment]
Could you provide your environment with the following command?
```
$ node -v
$ npm -v
```

**Comment by yillkid** [comment]
It success after I remove the repository and clone & install again, thank you.
