### ISSUE TITLE
Launch npm run dev failed

### ISSUE THREAD

**Issue by mgrassotti** [TangleID/TangleID#30]
Hi, 
I tried to install and launch the dev environment, but I got this error:
```
$ npm run dev

> tangleid@1.0.0 dev /Users/.../dev/TangleID
> node server.js

/Users/.../dev/TangleID/server.js:56
        server.get('/api/keyPairs', async (req, res) => {
                                          ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tangleid@1.0.0 dev: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tangleid@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2018-06-14T10_03_21_859Z-debug.log
```
Before I created a new `.env` file with the following content:
```
BACKEND=http://node2.puyuma.org:8000
API_HOST=http://localhost:3000/api
``` 
Am I doing sth wrong? 
Thanks

**Comment by ender503** [comment]
Could you provide your environment with the following command? 
```
$ node -v
$ npm -v
```

**Comment by mgrassotti** [comment]
Sure
```
$node -v
v6.11.4
$ npm -v
6.1.0
```
I updated npm after a first installation and trial. Not sure if this could be a problem.
Thanks

**Comment by ender503** [comment]
TangleID need at least node version v8.11.x.
You can change the node to the stable version(v8.11.2) with `nvm`.
```
$ nvm use 8.11.2
```
Then you could launch the dev environment.
```
$ npm run dev
```

**Comment by mgrassotti** [comment]
Great it worked thanks!
