### ISSUE TITLE
Failed to create new user

### ISSUE THREAD

**Issue by ender503** [TangleID/TangleID#67]
After submitting the new user form, the backend will be crashed and get the following message:
```
TangleID/utils/mam.node.js:9459
var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIR

Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! tangleid@1.0.0 dev: `node server.js`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the tangleid@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by ender503** [comment]
This bug is not related to the `mam.node.js`.

When I disable the `mam.node.js` and do the same thing, the backend is still crashed with the following message: 

```
Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! tangleid@1.0.0 dev: `node server.js`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the tangleid@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
```

**Comment by HexRabbit** [comment]
Have you updated urls in your `.env` file? 
`IRI_HOST=http://node.deviceproof.org:14265`

**Comment by ender503** [comment]
My `IRI_HOST ` is `http://node2.puyuma.org:8000`.
I'll change `IRI_HOST` and test with `http://node.deviceproof.org:14265`.

Thanks for reminding. 😃
